// AppSettings.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

namespace CelestiaAppComponent
{
    enum AppSettingBooleanEntry
    {
        UseFullDPI,
        EnableMSAA,
        IgnoreXboxWelcomeMessage,
        OnboardMessageDisplayed,
        GamepadInvertX,
        GamepadInvertY,
        GamepadEnableLeftThumbstick,
        GamepadEnableRightThumbstick,
    };

    enum AppSettingInt32Entry
    {
        GamepadRemapA,
        GamepadRemapB,
        GamepadRemapX,
        GamepadRemapY,
        GamepadRemapLT,
        GamepadRemapRT,
        GamepadRemapLB,
        GamepadRemapRB,
        GamepadRemapDpadUp,
        GamepadRemapDpadDown,
        GamepadRemapDpadLeft,
        GamepadRemapDpadRight,
    };

    enum AppSettingStringEntry
    {
        LanguageOverride,
        LastNewsID,
        DataDirectoryPath,
        ConfigFilePath,
    };

    enum AppSettingDoubleEntry
    {
        PickSensitivity,
    };

    [default_interface]
    runtimeclass AppSettings
    {
        AppSettings(Windows.Storage.ApplicationDataContainer settings);
        Boolean UseFullDPI;
        Boolean EnableMSAA;
        Boolean IgnoreXboxWelcomeMessage;
        Boolean OnboardMessageDisplayed;
        String LanguageOverride;
        String LastNewsID;
        String DataDirectoryPath;
        String ConfigFilePath;
        Double PickSensitivity;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapA;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapB;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapX;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapY;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapLT;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapRT;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapLB;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapRB;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapDpadUp;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapDpadDown;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapDpadLeft;
        CelestiaComponent.CelestiaGamepadAction GamepadRemapDpadRight;

        void SetBoolean(AppSettingBooleanEntry entry, Boolean value);
        Boolean GetBoolean(AppSettingBooleanEntry entry);
        void SetInt32(AppSettingInt32Entry entry, Int32 value);
        Int32 GetInt32(AppSettingInt32Entry entry);
        void SetString(AppSettingStringEntry entry, String value);
        String GetString(AppSettingStringEntry entry);
        void SetDouble(AppSettingDoubleEntry entry, Double value);
        Double GetDouble(AppSettingDoubleEntry entry);

        Boolean GamepadInvertX;
        Boolean GamepadInvertY;
        Boolean GamepadEnableLeftThumbstick;
        Boolean GamepadEnableRightThumbstick;

        void Save(Windows.Storage.ApplicationDataContainer settings);
    }
}
