// BookmarkHelper.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

import "BookmarkNode.idl";

namespace CelestiaAppComponent
{
    [default_interface]
    runtimeclass BookmarkHelper
    {
        static Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IObservableVector<BookmarkNode> > ReadBookmarks();
        static Windows.Foundation.IAsyncAction WriteBookmarks(Windows.Foundation.Collections.IObservableVector<BookmarkNode> value);
        static Windows.Foundation.Collections.IObservableVector<BookmarkNode> CreateEmptyList();
        static Microsoft.UI.Xaml.Interop.IBindableObservableVector ConvertToBindable(Windows.Foundation.Collections.IObservableVector<BookmarkNode> list);
    }
}
