namespace CelestiaAppComponent
{
    [default_interface]
    unsealed runtimeclass BrowserAction
    {
        String Name{ get; };
    }

    [default_interface]
    runtimeclass BrowserGetInfoAction : BrowserAction
    {
        BrowserGetInfoAction();
    }

    [default_interface]
    runtimeclass BrowserShowSubsystemAction : BrowserAction
    {
        BrowserShowSubsystemAction();
    }

    [default_interface]
    runtimeclass BrowserInputAction : BrowserAction
    {
        BrowserInputAction(String name, Int16 code);
        Int16 Code{ get; };
    }

    [default_interface]
    runtimeclass BrowserMarkMenuItem
    {
        BrowserMarkMenuItem(Boolean mark, CelestiaComponent.CelestiaMarkerRepresentation marker);
        String Title{ get; };
        Boolean Mark{ get; };
        CelestiaComponent.CelestiaMarkerRepresentation Marker{ get; };
    }

    [default_interface]
    runtimeclass BrowserMarkAction : BrowserAction
    {
        BrowserMarkAction();
        Windows.Foundation.Collections.IObservableVector<BrowserMarkMenuItem> MenuItems{ get; };
    }

    [default_interface]
    runtimeclass BrowserItem
    {
        BrowserItem(CelestiaComponent.CelestiaBrowserItem item);
        String ItemName{ get; };
        Boolean IsExpanded;
        CelestiaComponent.CelestiaBrowserItem Item{ get; };
        Windows.Foundation.Collections.IObservableVector<BrowserItem> Children{ get; };
        Microsoft.UI.Xaml.Interop.IBindableObservableVector BindableChildren{ get; };
        static Microsoft.UI.Xaml.Interop.IBindableObservableVector ConvertToBindable(Windows.Foundation.Collections.IObservableVector<BrowserItem> list);
    }

    [default_interface]
    runtimeclass BrowserItemTab
    {
        BrowserItemTab(Windows.Foundation.Collections.IVector<BrowserItem> children, String tabName);
        String TabName{ get; };
        Windows.Foundation.Collections.IObservableVector<BrowserItem> Children{ get; };
    }
}
