// ContentDialogHelper.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

namespace CelestiaAppComponent
{
    [default_interface]
    runtimeclass ContentDialogHelper
    {
        static Windows.Foundation.IAsyncAction ShowAlert(Microsoft.UI.Xaml.UIElement element, String message);
        static Windows.Foundation.IAsyncAction ShowAlert(Microsoft.UI.Xaml.UIElement element, String message, String content);
        static Windows.Foundation.IAsyncOperation<Boolean> ShowOption(Microsoft.UI.Xaml.UIElement element, String message);
        static Windows.Foundation.IAsyncOperation<Boolean> ShowOption(Microsoft.UI.Xaml.UIElement element, String message, String content);
        static Windows.Foundation.IAsyncOperation<String> GetText(Microsoft.UI.Xaml.UIElement element, String message);
        static Windows.Foundation.IAsyncOperation<String> GetText(Microsoft.UI.Xaml.UIElement element, String message, String placeholder);
        static Windows.Foundation.IAsyncAction ShowText(Microsoft.UI.Xaml.UIElement element, String title, String text);
        static Windows.Foundation.IAsyncOperation<Microsoft.UI.Xaml.Controls.ContentDialogResult> ShowContentDialogAsync(Microsoft.UI.Xaml.UIElement element, Microsoft.UI.Xaml.Controls.ContentDialog contentDialog);
    }
}
