namespace CelestiaAppComponent
{
    [default_interface]
    runtimeclass LocalizationHelper
    {
        static String Locale;
        static String Localize(String original);
        static String FromWindowsTag(String tag);
        static String ToWindowsTag(String locale);
    }
}
