// RequestResult.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

namespace CelestiaAppComponent
{
    [default_interface]
    runtimeclass RequestResultInfo
    {
        RequestResultInfo(String detail, String reason);
        String Detail{ get; };
        String Reason{ get; };
    }

    [default_interface]
    runtimeclass RequestResult
    {
        RequestResult(RequestResultInfo info, Int32 status);
        RequestResultInfo Info{ get; };
        Int32 Status{ get; };
        static RequestResult TryParse(String data);
    }
}
