// SystemInformation.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

namespace CelestiaAppComponent
{
    [default_interface]
    runtimeclass SystemInformation
    {
        static SystemInformation Instance{ get; };
        Windows.ApplicationModel.PackageVersion ApplicationVersion{ get; };
        String OperatingSystem{ get; };
        String OperatingSystemVersion{ get; };
        Windows.System.ProcessorArchitecture OperatingSystemArchitecture{ get; };
        String OperatingSystemArchitectureString{ get; };
        String DeviceModel{ get; };
        String DeviceManufacturer{ get; };
        String DeviceFamily{ get; };
    }
}
