jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'windows-2025'

  variables:
    solution: 'CelestiaUWP/CelestiaUWP.sln'
    buildConfiguration: 'Release'
    contentCommitHash: ${{ '9cdd5d71ae696fa9803f33e512e918bd9799e49c' }}
    buildType: ${{ parameters.buildType }}
    arch: ${{ parameters.arch }}
    dependencyVersion: '1.0.18'
    angleVersion: '1.1.10'

  steps:
  - checkout: Celestia
    fetchDepth: 0
  - checkout: CelestiaContent
    fetchDepth: 0
  - checkout: CelestiaLocalization
    fetchDepth: 0
  - checkout: self
    fetchDepth: 0

  - pwsh: |
      $vs = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -products * -requires Microsoft.Component.MSBuild -latest -utf8 -format json | ConvertFrom-Json
      $msbuild = Join-Path $vs[0].installationPath "MSBuild" "Current" "Bin" "MSBuild.exe"
      Write-Host "##vso[task.setvariable variable=msbuild;]$msbuild"
    displayName: 'Find MSBuild'

  - script: |
      choco install sentry-cli imagemagick
    displayName: 'Install Build Dependencies'

  - script: |
      cd Celestia
      git checkout origin/$(Build.SourceBranchName)
      cd ../CelestiaLocalization
      git checkout origin/$(Build.SourceBranchName)
    displayName: 'Checkout Branch'
    condition: ne( variables['Build.Reason'], 'PullRequest' )

  - script: |
      cd Celestia
      git checkout origin/$(System.PullRequest.TargetBranch)
      cd ../CelestiaLocalization
      git checkout origin/$(System.PullRequest.TargetBranch)
    displayName: 'Checkout Branch (PR)'
    condition: eq( variables['Build.Reason'], 'PullRequest' )

  - script: |
      cd CelestiaContent
      git checkout $(contentCommitHash)
    displayName: 'Checkout Content'

  - script: |
      cd CelestiaUWP
      git apply patches/nuget/nuget-$(arch).patch --ignore-whitespace --whitespace=nowarn
    displayName: 'Apply Nuget Patches'

  - script: |
      call "$(System.DefaultWorkingDirectory)\CelestiaUWP\scripts\downsize_textures.bat" "$(System.DefaultWorkingDirectory)\CelestiaUWP"
    displayName: 'Running imagemagick'

  - script: |
      call "$(System.DefaultWorkingDirectory)\CelestiaUWP\scripts\run_gperf.bat" "$(System.DefaultWorkingDirectory)\CelestiaUWP"
    displayName: 'Running gperf'

  - bash: |
      cd CelestiaUWP

      TO_REPLACE="SENTRY-DSN"
      NEW_STRING=$(SENTRY-DSN)
      sed -ie "s#${TO_REPLACE}#${NEW_STRING}#g" CelestiaWinUI/App.xaml.cpp

      echo "New Content:"
      cat CelestiaWinUI/App.xaml.cpp
    displayName: 'Replace Sentry Placeholder'

  - script: |
      call "$(System.DefaultWorkingDirectory)\CelestiaUWP\scripts\copy_general_data.bat" "$(System.DefaultWorkingDirectory)\CelestiaUWP" "$(System.DefaultWorkingDirectory)\CelestiaUWP\CelestiaWinUI\Resources"
    displayName: 'Copy General Data'

  - script: |
      call "$(System.DefaultWorkingDirectory)\CelestiaUWP\scripts\convert_po.bat" "$(System.DefaultWorkingDirectory)\CelestiaUWP" "$(System.DefaultWorkingDirectory)\CelestiaUWP\CelestiaWinUI\Resources"
    displayName: 'Convert POs'

  - task: NuGetToolInstaller@1
    displayName: 'Install Nuget'

  - pwsh: |
      $packageName = "celestia-windows-$(arch)-dependencies.$(dependencyVersion).nupkg"
      $releaseUrl = "https://github.com/celestiamobile/windows-dependencies/releases/download/$(dependencyVersion)/$packageName"

      Write-Host "Downloading $packageName from GitHub releases..."
      Write-Host "URL: $releaseUrl"

      # Download the package to current working directory
      Invoke-WebRequest -Uri $releaseUrl -OutFile $packageName
      Write-Host "Successfully downloaded $packageName to current directory"
    displayName: 'Download Dependencies from GitHub'

  - pwsh: |
      $packageName = "Celestia.ANGLE.$(angleVersion).nupkg"
      $releaseUrl = "https://github.com/celestiamobile/angle-windows/releases/download/angle-$(angleVersion)/$packageName"

      Write-Host "Downloading $packageName from GitHub releases..."
      Write-Host "URL: $releaseUrl"

      # Download the package to current working directory
      Invoke-WebRequest -Uri $releaseUrl -OutFile $packageName
      Write-Host "Successfully downloaded $packageName to current directory"
    displayName: 'Download ANGLE from GitHub'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: 'install celestia-windows-$(arch)-dependencies -source $(System.DefaultWorkingDirectory) -OutputDirectory CelestiaUWP/packages'
    displayName: 'Install Dependencies'

  - task: NuGetCommand@2
    inputs:
      command: custom
      arguments: 'install Celestia.ANGLE -source $(System.DefaultWorkingDirectory) -OutputDirectory CelestiaUWP/packages'
    displayName: 'Install ANGLE'

  - script: |
      RD Celestia\.git /S /Q
      RD CelestiaContent\.git /S /Q
      RD CelestiaUWP\.git /S /Q
    displayName: 'Remove Unneeded Files'

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
      feedsToUse: 'select'
      vstsFeed: '9f9dcde1-dcba-4537-8214-71c8a03b99a0/14bb1031-e6b2-40ac-b287-73e7fcb5900e'
    displayName: 'Restore Solution'

  - task: DownloadSecureFile@1
    name: signingCert
    displayName: 'Download CA certificate'
    inputs:
      secureFile: '3d.pfx'

  - pwsh: |
      $CurrentDir = Get-Location
      New-Item -Name "AppPackages" -ItemType "directory"
      & "$(msbuild)" /m /t:CelestiaWinUI /p:Configuration=Release /p:Platform="$(arch)" /p:AppxBundlePlatforms="$(arch)" /p:AppxPackageDir="${CurrentDir}\AppPackages\" /p:AppxBundle=Never /p:UapAppxPackageBuildMode=CI /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="" /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)" /p:GenerateAppxPackageOnBuild=true "CelestiaUWP.sln"
    workingDirectory: '$(System.DefaultWorkingDirectory)\CelestiaUWP'
    displayName: 'Build MSIXUpload'
    condition: eq( variables['buildType'], 'msixupload' )

  - pwsh: |
      $CurrentDir = Get-Location
      New-Item -Name "AppPackages" -ItemType "directory"
      & "$(msbuild)" /m /t:CelestiaWinUI /p:Configuration=Release /p:Platform="$(arch)" /p:AppxBundlePlatforms="$(arch)" /p:AppxPackageDir="${CurrentDir}\AppPackages\" /p:AppxBundle=Never /p:UapAppxPackageBuildMode=SideLoadOnly /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="" /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)" /p:GenerateAppxPackageOnBuild=true "CelestiaUWP.sln"
    workingDirectory: '$(System.DefaultWorkingDirectory)\CelestiaUWP'
    displayName: 'Build Sideload'
    condition: eq( variables['buildType'], 'sideload' )

  - pwsh: |
      $packageManifestContent = Get-Content -Path CelestiaWinUI\Package.appxmanifest -Raw
      $packageManifestXML = [xml]$packageManifestContent
      $version = $packageManifestXML.Package.Identity.Version

      New-Item -Name "Symbols" -ItemType "directory"
      Rename-Item -Path "AppPackages\CelestiaWinUI_${version}_$(arch)_Test\CelestiaWinUI_${version}_$(arch).appxsym" -NewName "symbols.zip"
      Expand-Archive "AppPackages\CelestiaWinUI_${version}_$(arch)_Test\symbols.zip" -Destination Symbols
      Rename-Item -Path "AppPackages\CelestiaWinUI_${version}_$(arch)_Test\symbols.zip" -NewName "CelestiaWinUI_${version}_$(arch).appxsym"
    displayName: 'Move Symbols'
    workingDirectory: '$(System.DefaultWorkingDirectory)\CelestiaUWP'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Symbols'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)\CelestiaUWP\Symbols'
      ArtifactName: '$(buildType)-$(arch)-symbols'
      publishLocation: Container

  - script: |
      sentry-cli debug-files upload -o celestia-vs -p windows --auth-token $(SENTRY_AUTH_TOKEN) --include-sources Symbols
    workingDirectory: '$(System.DefaultWorkingDirectory)\CelestiaUWP'
    displayName: 'Upload Symbols'

  - pwsh: |
      $packageManifestContent = Get-Content -Path CelestiaWinUI\Package.appxmanifest -Raw
      $packageManifestXML = [xml]$packageManifestContent
      $version = $packageManifestXML.Package.Identity.Version

      New-Item -Name "Output" -ItemType "directory"

      Get-ChildItem -Path "packages\Celestia.ANGLE.$(angleVersion)\build\native\$(arch)\bin" -Include *.pdb -Recurse | Copy-Item -Destination Symbols\
      Get-ChildItem -Path "packages\celestia-windows-$(arch)-dependencies.$(dependencyVersion)\installed\$(arch)-windows\bin" -Include *.pdb -Recurse | Copy-Item -Destination Symbols\
      Compress-Archive -Path Symbols\* -Destination "Output\symbols.zip"
      Rename-Item -Path "Output\symbols.zip" -NewName "CelestiaWinUI_${version}_$(arch).appxsym"

      New-Item -Name "MSIX" -ItemType "directory"
      Copy-Item -Path "AppPackages\CelestiaWinUI_${version}_$(arch)_Test\CelestiaWinUI_${version}_$(arch).msix" -Destination "MSIX"

      Remove-Item -Path "AppPackages" -Recurse -Force
      New-Item -Name "AppPackages" -ItemType "directory"
      Move-Item -Path "MSIX\CelestiaWinUI_${version}_$(arch).msix" -Destination "AppPackages"
      Move-Item -Path "Output\CelestiaWinUI_${version}_$(arch).appxsym" -Destination "AppPackages"
    workingDirectory: '$(System.DefaultWorkingDirectory)\CelestiaUWP'
    displayName: 'Bundle'
    condition: eq( variables['buildType'], 'msixupload' )

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)\CelestiaUWP\AppPackages'
      ArtifactName: '$(buildType)-$(arch)'
      publishLocation: Container
