jobs:
- job: Publish
  displayName: 'Publish'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: 'Universal'

  - task: AppCenterDistribute@3
    displayName: 'Publish to App Center'
    inputs:
      serverEndpoint: 'UWPCelestiaAppCenter'
      appSlug: 'CelestiaProject/Celestia-4'
      appFile: '$(System.ArtifactsDirectory)\Universal\**\*.msixupload'
      symbolsOption: 'UWP'
      appxsymPath: '$(System.ArtifactsDirectory)\Universal\**\*.appxsym'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Internal testing only.'
      destinationType: 'groups'

  - script: |
      del $(System.ArtifactsDirectory)\Universal\*.msixupload
      del $(System.ArtifactsDirectory)\Universal\*.appxsym /s /q
    displayName: 'Remove .msixupload, .appxsym'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\Universal'
      ArtifactName: CelestiaSL
      publishLocation: Container
