jobs:
- job: Publish
  displayName: 'Publish'
  pool:
    vmImage: 'windows-2022'

  variables:
    publishType: ${{ parameters.publishType }}

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Sideload Artifacts'
    inputs:
      artifactName: 'sideload'

  - script: |
      DEL $(System.ArtifactsDirectory)\$(publishType)\*.msixsym /S /Q
    displayName: 'Remove .msixsym'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\$(publishType)'
      ArtifactName: CelestiaSL
      publishLocation: Container