// CelestiaSimulation.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

import "CelestiaCompletion.idl";
import "CelestiaDestination.idl";
import "CelestiaEclipse.idl";
import "CelestiaGotoLocation.idl";
import "CelestiaObserver.idl";
import "CelestiaSelection.idl";
import "CelestiaUniverse.idl";

namespace CelestiaComponent
{
    enum CelestiaEclipseAction
    {
        SetTime = 0,
        NearEclipsedBody = 1,
        FromEclipsedBodySurface = 2,
        FromOcculterSurface = 3,
        BehindOcculter = 4
    };

    [default_interface]
    runtimeclass CelestiaSimulation
    {
        CelestiaSelection Selection;
        Windows.Foundation.DateTime Time;
        Double JulianDay;
        CelestiaUniverse Universe{ get; };
        CelestiaObserver ActiveObserver{ get; };

        CelestiaSelection Find(String name);
        void GoToDestination(CelestiaDestination destination);
        void GoToLocation(CelestiaGotoLocation location);
        void PerformEclipseAction(CelestiaEclipse eclipse, CelestiaEclipseAction action);
        void ReverseOrientation();

        CelestiaCompletion[] GetCompletion(String name);
    }
}
