// CelestiaStarCatalog.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

import "CelestiaStar.idl";

namespace CelestiaComponent
{
    [default_interface]
    runtimeclass CelestiaStarCatalog
    {
        Int32 Count{ get; };
        CelestiaStar StarAt(Int32 index);
        String StarName(CelestiaStar star);
    }
}
