//
// Copyright © 2021 Celestia Development Team. All rights reserved.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//

import "CelestiaAstroObject.idl";
import "CelestiaOrbit.idl";
import "CelestiaPlanetarySystem.idl";
import "CelestiaRotationModel.idl";
import "CelestiaTimeline.idl";

namespace CelestiaComponent
{
    [flags]
    enum CelestiaBodyType
    {
        Planet = 0x01,
        Moon = 0x02,
        Asteroid = 0x04,
        Comet = 0x08,
        Spacecraft = 0x10,
        Invisible = 0x20,
        Barycenter = 0x40,           // Not used (invisible is used instead)
        SmallBody = 0x80,            // Not used
        DwarfPlanet = 0x100,
        Stellar = 0x200,             // only used for orbit mask
        SurfaceFeature = 0x400,
        Component = 0x800,
        MinorMoon = 0x1000,
        Diffuse = 0x2000,
        Unknown = 0x10000,
    };

    [default_interface]
    runtimeclass CelestiaBody : CelestiaAstroObject
    {
        String Name{ get; };
        CelestiaBodyType Type{ get; };
        String[] AlternateSurfaceNames{ get; };
        String InfoURL{ get; };
        CelestiaPlanetarySystem System{ get; };
        Boolean HasRings{ get; };
        Boolean HasAtmosphere{ get; };
        Boolean IsEllipsoid{ get; };
        Single Radius{ get; };
        CelestiaTimeline Timeline{ get; };
        Boolean CanBeUsedAsCockpit{ get; };

        CelestiaOrbit OrbitAtTime(Double julianDay);
        CelestiaRotationModel RotationModelAtTime(Double julianDay);
    }
}
