import "CelestiaSelection.idl";
import "CelestiaSimulation.idl";

namespace CelestiaComponent
{
    delegate void CelestiaLoadCallback(String status);
    delegate void CelestiaContextMenuCallback(Int32 x, Int32 y, CelestiaSelection selection);

    [default_interface]
    runtimeclass CelestiaAppCore
    {
        CelestiaAppCore();

        Boolean StartSimulation(String configFileName, String[] extraDirectories, CelestiaLoadCallback callback);
        Boolean StartRenderer();
        void Tick();
        void Draw();
        void Resize(Int32 width, Int32 height);
        void Start();
        void SetDPI(Int32 dpi);
        void MouseMove(Single x, Single y, Int32 button);
        void MouseButtonUp(Single x, Single y, Int32 button);
        void MouseButtonDown(Single x, Single y, Int32 button);
        void CharEnter(Int16 input);
        void SetContextMenuHandler(CelestiaContextMenuCallback handler);
        CelestiaSimulation Simulation{ get; };

        static void InitGL();
        static void SetLocaleDirectory(String localeDirectory);
        static String LocalizedString(String original);
    }
}
