import "CelestiaAstroObject.idl";

namespace CelestiaComponent
{
    [default_interface]
    runtimeclass CelestiaSelection
    {
        CelestiaSelection(CelestiaAstroObject object);
        CelestiaAstroObject Object{ get; };
        Boolean IsEmpty{ get; };
    }
}
