//
// Copyright © 2021 Celestia Development Team. All rights reserved.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//

namespace CelestiaComponent
{
    delegate Boolean CelestiaRendererEngineStartedHandler(Int32 sampleCount);
    delegate void CelestiaRendererTask();

    [default_interface]
    runtimeclass CelestiaRenderer
    {
        CelestiaRenderer(Boolean enableMultisample, CelestiaRendererEngineStartedHandler engineStarted);
        void Start();
        void Stop();
        void Pause();
        void Resume();
        void SetSurface(Microsoft.UI.Xaml.Controls.SwapChainPanel surface, Single scale);
        void SetCorePointer(Int64 core);
        void EnqueueTask(CelestiaRendererTask task);
        void SetPreRenderTask(CelestiaRendererTask task);
        void MakeContextCurrent();
    }
}
