import "CelestiaDestination.idl";
import "CelestiaSelection.idl";
import "CelestiaUniverse.idl";

namespace CelestiaComponent
{
    [default_interface]
    runtimeclass CelestiaSimulation
    {
        CelestiaSelection Selection;
        CelestiaUniverse Universe{ get; };

        CelestiaSelection Find(String name);
        void GoToDestination(CelestiaDestination destination);
    }
}