namespace CelestiaComponent
{
    [default_interface]
    runtimeclass CelestiaHelper
    {
        static Double JulianDayFromDateTime(Windows.Foundation.DateTime dateTime);
        static Windows.Foundation.DateTime DateTimeFromJulianDay(Double julianDay);
    }
}
