import "CelestiaSelection.idl";
import "CelestiaStarCatalog.idl";
import "CelestiaDSOCatalog.idl";

namespace CelestiaComponent
{
    [default_interface]
    runtimeclass CelestiaUniverse
    {
        CelestiaSelection Find(String name);
        String NameForSelection(CelestiaSelection selection);

        CelestiaStarCatalog StarCatalog{ get; };
        CelestiaDSOCatalog DSOCatalog{ get; };
    }
}