import "CelestiaAstroObject.idl";

namespace CelestiaComponent
{
    [default_interface]
    unsealed runtimeclass CelestiaDSO : CelestiaAstroObject
    {
        String Type{ get; };
        String InfoURL{ get; };
    }
}
