namespace CelestiaComponent
{
    delegate void CelestiaLoadCallback(String status);

    [default_interface]
    runtimeclass CelestiaAppCore
    {
        CelestiaAppCore();

        Boolean StartSimulation(String configFileName, String[] extraDirectories, CelestiaLoadCallback callback);
        Boolean StartRenderer();
        void Tick();
        void Draw();
        void Resize(Int32 width, Int32 height);
        void Start();
        void SetDPI(Int32 dpi);
        void MouseMove(Single x, Single y, Int32 button);
        void MouseButtonUp(Single x, Single y, Int32 button);
        void MouseButtonDown(Single x, Single y, Int32 button);

        static void InitGL();
        static void SetLocaleDirectory(String localeDirectory);
    }
}
