// CelestiaOrbit.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

import "CelestiaVector.idl";

namespace CelestiaComponent
{
    [default_interface]
    runtimeclass CelestiaOrbit
    {
        Boolean IsPeriodic{ get; };
        Double Period{ get; };
        Double BoundingRadius{ get; };
        Double ValidBeginTime{ get; };
        Double ValidEndTime{ get; };

        CelestiaVector VelocityAtTime(Double julianDay);
        CelestiaVector PositionAtTime(Double julianDay);
    }
}
