//
// Copyright © 2021 Celestia Development Team. All rights reserved.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//

import "CelestiaDestination.idl";
import "CelestiaScript.idl";
import "CelestiaSelection.idl";
import "CelestiaSimulation.idl";

namespace CelestiaComponent
{
    enum CelestiaFontStyle
    {
        Normal = 0,
        Large = 1
    };

    [flags]
    enum CelestiaMouseButton
    {
        Left = 1,
        Middle = 2,
        Right = 4
    };

    enum CelestiaMeasurementSystem
    {
        Metric = 0,
        Imperial = 1,
    };

    enum CelestiaJoystickAxis
    {
        X = 0,
        Y = 1,
        Z = 2,
        RX = 3,
        RY = 4,
        RZ = 5,
    };

    enum CelestiaJoystickButton
    {
        Button1 = 0,
        Button2 = 1,
        Button3 = 2,
        Button4 = 3,
        Button5 = 4,
        Button6 = 5,
        Button7 = 6,
        Button8 = 7,
    };

    enum Cursor
    {
        Arrow = 0,
        UpArrow = 1,
        Cross = 2,
        InvertedCross = 3,
        Wait = 4,
        Busy = 5,
        Ibeam = 6,
        SizeVer = 7,
        SizeHor = 8,
        SizeBDiag = 9,
        SizeFDiag = 10,
        SizeAll = 11,
        SplitV = 12,
        SplitH = 13,
        PointingHand = 14,
        Forbidden = 15,
        WhatsThis = 16,
    };

    enum CelestiaLayoutDirection
    {
        LTR = 0,
        RTL = 1,
    };

    delegate void CelestiaLoadCallback(String status);

    [default_interface]
    runtimeclass ShowContextMenuArgs
    {
        Single X{ get; };
        Single Y{ get; };
        CelestiaSelection Selection{ get; };
    }

    [default_interface]
    runtimeclass ChangeCursorArgs
    {
        Cursor Cursor{ get; };
    }

    [default_interface]
    runtimeclass FatalErrorArgs
    {
        String Message{ get; };
    }

    enum SystemAccessRequestResult
    {
        Unknown = 0,
        Granted = 1,
        Denied  = 2,
    };

    [default_interface]
    runtimeclass SystemAccessRequestArgs
    {
        SystemAccessRequestResult Result;
    }

    [default_interface]
    runtimeclass CelestiaAppCore
    {
        CelestiaAppCore();

        Boolean StartSimulation(String configFileName, String[] extraDirectories, CelestiaLoadCallback callback);
        Boolean StartRenderer();
        void Tick();
        void Draw();
        void Resize(Int32 width, Int32 height);
        Int32 GetWidth();
        Int32 GetHeight();
        void Start();
        void SetDPI(Int32 dpi);
        void SetSafeAreaInsets(Int32 left, Int32 top, Int32 right, Int32 bottom);
        void MouseMove(Single x, Single y, CelestiaMouseButton button);
        void MouseButtonUp(Single x, Single y, CelestiaMouseButton button);
        void MouseButtonDown(Single x, Single y, CelestiaMouseButton button);
        void MouseWheel(Single motion, Int32 modifiers);
        void CharEnter(Int16 input);
        void CharEnter(Int16 input, Int32 modifiers);
        void KeyUp(Int32 key, Int32 modifiers);
        void KeyDown(Int32 key, Int32 modifiers);
        void JoystickButtonDown(CelestiaJoystickButton button);
        void JoystickButtonUp(CelestiaJoystickButton button);
        void JoystickAxis(CelestiaJoystickAxis axis, Single amount);
        void SetHudFont(String fontPath, Int32 collectionIndex, Int32 fontSize);
        void SetHudTitleFont(String fontPath, Int32 collectionIndex, Int32 fontSize);
        void SetRenderFont(String fontPath, Int32 collectionIndex, Int32 fontSize, CelestiaFontStyle fontStyle);
        void RunScript(String path);
        void RunDemo();
        void GoToURL(String url);
        Boolean SaveScreenshot(String filePath);
        CelestiaDestination[] Destinations{ get; };
        CelestiaSimulation Simulation{ get; };
        String CurrentURL{ get; };
        String RenderInfo{ get; };
        Int64 Pointer{ get; };

        static void InitGL();
        static String Language{ get; };
        static void SetLocaleDirectory(String localeDirectory, String locale);
        static void SetUpLocale();
        static String LocalizedString(String original, String domain);
        static String LocalizedString(String original, String context, String domain);
        static CelestiaScript[] ReadScripts(String directory, Boolean deepScan);

        Boolean ShowStars;
        Boolean ShowPlanets;
        Boolean ShowDwarfPlanets;
        Boolean ShowMoons;
        Boolean ShowMinorMoons;
        Boolean ShowAsteroids;
        Boolean ShowComets;
        Boolean ShowSpacecrafts;
        Boolean ShowGalaxies;
        Boolean ShowGlobulars;
        Boolean ShowNebulae;
        Boolean ShowOpenClusters;
        Boolean ShowDiagrams;
        Boolean ShowBoundaries;
        Boolean ShowCloudMaps;
        Boolean ShowNightMaps;
        Boolean ShowAtmospheres;
        Boolean ShowCometTails;
        Boolean ShowPlanetRings;
        Boolean ShowMarkers;
        Boolean ShowOrbits;
        Boolean ShowFadingOrbits;
        Boolean ShowEcliptic;
        Boolean ShowPartialTrajectories;
        Boolean ShowSmoothLines;
        Boolean ShowEclipseShadows;
        Boolean ShowRingShadows;
        Boolean ShowCloudShadows;
        Boolean ShowAutoMag;
        Boolean ShowCelestialSphere;
        Boolean ShowEclipticGrid;
        Boolean ShowHorizonGrid;
        Boolean ShowGalacticGrid;
        Boolean ShowStarLabels;
        Boolean ShowPlanetLabels;
        Boolean ShowMoonLabels;
        Boolean ShowConstellationLabels;
        Boolean ShowGalaxyLabels;
        Boolean ShowGlobularLabels;
        Boolean ShowNebulaLabels;
        Boolean ShowOpenClusterLabels;
        Boolean ShowAsteroidLabels;
        Boolean ShowSpacecraftLabels;
        Boolean ShowLocationLabels;
        Boolean ShowCometLabels;
        Boolean ShowDwarfPlanetLabels;
        Boolean ShowMinorMoonLabels;
        Boolean ShowLatinConstellationLabels;
        Boolean ShowPlanetOrbits;
        Boolean ShowMoonOrbits;
        Boolean ShowAsteroidOrbits;
        Boolean ShowSpacecraftOrbits;
        Boolean ShowCometOrbits;
        Boolean ShowStellarOrbits;
        Boolean ShowDwarfPlanetOrbits;
        Boolean ShowMinorMoonOrbits;
        Boolean ShowCityLabels;
        Boolean ShowObservatoryLabels;
        Boolean ShowLandingSiteLabels;
        Boolean ShowCraterLabels;
        Boolean ShowVallisLabels;
        Boolean ShowMonsLabels;
        Boolean ShowPlanumLabels;
        Boolean ShowChasmaLabels;
        Boolean ShowPateraLabels;
        Boolean ShowMareLabels;
        Boolean ShowRupesLabels;
        Boolean ShowTesseraLabels;
        Boolean ShowRegioLabels;
        Boolean ShowChaosLabels;
        Boolean ShowTerraLabels;
        Boolean ShowAstrumLabels;
        Boolean ShowCoronaLabels;
        Boolean ShowDorsumLabels;
        Boolean ShowFossaLabels;
        Boolean ShowCatenaLabels;
        Boolean ShowMensaLabels;
        Boolean ShowRimaLabels;
        Boolean ShowUndaeLabels;
        Boolean ShowReticulumLabels;
        Boolean ShowPlanitiaLabels;
        Boolean ShowLineaLabels;
        Boolean ShowFluctusLabels;
        Boolean ShowFarrumLabels;
        Boolean ShowEruptiveCenterLabels;
        Boolean ShowOtherLabels;
        Int32 Resolution;
        Int32 StarStyle;
        Int32 HudDetail;
        Int32 DateFormat;
        Int32 StarColors;
        Single AmbientLightLevel;
        Single FaintestVisible;
        Single GalaxyBrightness;
        Single MinimumFeatureSize;
        Single DistanceLimit;
        Single TintSaturation;

        Boolean ShowBodyAxes;
        Boolean ShowFrameAxes;
        Boolean ShowSunDirection;
        Boolean ShowVelocityVector;
        Boolean ShowPlanetographicGrid;
        Boolean ShowTerminator;

        Boolean EnableReverseWheel;
        Boolean EnableRayBasedDragging;
        Boolean EnableFocusZooming;
        Boolean EnableAlignCameraToSurfaceOnLand;

        Int32 TimeZone;
        Int32 MeasurementSystem;
        Int32 TemperatureScale;
        Int32 ScriptSystemAccessPolicy;

        Single PickTolerance;

        CelestiaLayoutDirection LayoutDirection;

        event Windows.Foundation.EventHandler<ShowContextMenuArgs> ShowContextMenu;
        event Windows.Foundation.EventHandler<ChangeCursorArgs> ChangeCursor;
        event Windows.Foundation.EventHandler<FatalErrorArgs> FatalError;
        event Windows.Foundation.EventHandler<SystemAccessRequestArgs> SystemAccessRequest;
    }
}
