//
// Copyright © 2021 Celestia Development Team. All rights reserved.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//

import "CelestiaSelection.idl";

namespace CelestiaComponent
{
    enum CelestiaGotoLocationDistanceUnit
    {
        KM = 0,
        Radii = 1,
        AU = 2
    };

    [default_interface]
    runtimeclass CelestiaGotoLocation
    {
        CelestiaGotoLocation(CelestiaSelection selection, Windows.Foundation.IReference<Single> latitude, Windows.Foundation.IReference<Single> longitude, Windows.Foundation.IReference<Double> distance, Windows.Foundation.IReference<CelestiaGotoLocationDistanceUnit> unit);
    }
}
