import "CelestiaStar.idl";
import "CelestiaBody.idl";
import "CelestiaBrowserItem.idl";
import "CelestiaSelection.idl";
import "CelestiaStarCatalog.idl";
import "CelestiaDSOCatalog.idl";

namespace CelestiaComponent
{
    [default_interface]
    runtimeclass CelestiaUniverse
    {
        CelestiaSelection Find(String name);
        String NameForSelection(CelestiaSelection selection);

        CelestiaBrowserItem[] ChildrenForStar(CelestiaStar star, CelestiaBrowserItemChildrenProvider provider);
        CelestiaBrowserItem[] ChildrenForBody(CelestiaBody body, CelestiaBrowserItemChildrenProvider provider);

        CelestiaStarCatalog StarCatalog{ get; };
        CelestiaDSOCatalog DSOCatalog{ get; };
    }
}