// CelestiaStarBrowser.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

import "CelestiaStar.idl";

namespace CelestiaComponent
{
    enum CelestiaStarBrowserType
    {
        Nearest = 0,
        Brighter = 1,
        Brightest = 2,
        WithPlants = 3
    };

    [default_interface]
    runtimeclass CelestiaStarBrowser: Windows.Foundation.IClosable
    {
        CelestiaStar[] Stars{ get; };
    }
}
