import "CelestiaDestination.idl";
import "CelestiaEclipse.idl";
import "CelestiaGotoLocation.idl";
import "CelestiaSelection.idl";
import "CelestiaStarBrowser.idl";
import "CelestiaUniverse.idl";

namespace CelestiaComponent
{
    [default_interface]
    runtimeclass CelestiaSimulation
    {
        CelestiaSelection Selection;
        Windows.Foundation.DateTime Time;
        CelestiaUniverse Universe{ get; };

        CelestiaSelection Find(String name);
        CelestiaStarBrowser StarBrowser(CelestiaStarBrowserType type);
        void GoToDestination(CelestiaDestination destination);
        void GoToLocation(CelestiaGotoLocation location);
        void GoToEclipse(CelestiaEclipse eclipse);
    }
}