import "CelestiaBody.idl";

namespace CelestiaComponent
{
    enum CelestiaEclipseKind
    {
        solar = 1,
        lunar = 2,
        solarAndLunar = 3
    };

    [default_interface]
    runtimeclass CelestiaEclipse
    {
        CelestiaBody Occulter{ get; };
        CelestiaBody Receiver{ get; };
        Windows.Foundation.DateTime StartTime{ get; };
        Windows.Foundation.DateTime EndTime{ get; };
    }
}
