namespace CelestiaComponent
{
    delegate Boolean CelestiaRendererEngineStartedHandler();
    delegate void CelestiaRendererTask();

    [default_interface]
    runtimeclass CelestiaRenderer
    {
        CelestiaRenderer(Boolean enableMultisample, CelestiaRendererEngineStartedHandler engineStarted);
        void Start();
        void Stop();
        void Pause();
        void Resume();
        void SetSurface(Windows.UI.Xaml.Controls.SwapChainPanel surface, Single scale);
        void SetSize(Int32 width, Int32 height);
        void SetCorePointer(Int64 core);
        void EnqueueTask(CelestiaRendererTask task);
    }
}
