// BrowserItemUserControl.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

import "InfoControlStrip.idl";

namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass BrowserItemUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        BrowserItemUserControl(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer, CelestiaAppComponent.BrowserItemTab item);
        BrowserItemUserControl(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer, CelestiaAppComponent.BrowserItemTab item, Boolean preserveMargin);

        Microsoft.UI.Xaml.Interop.IBindableObservableVector RootItem{ get; };

        event Windows.Foundation.EventHandler<InfoGetInfoArgs> GetInfo;
    }
}
