import "InfoControlStrip.idl";

namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass BrowserItemUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        BrowserItemUserControl(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer, CelestiaAppComponent.BrowserItemTab item);
        BrowserItemUserControl(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer, CelestiaAppComponent.BrowserItemTab item, Boolean preserveMargin);

        Microsoft.UI.Xaml.Interop.IBindableObservableVector RootItem{ get; };

        event Windows.Foundation.EventHandler<InfoGetInfoArgs> GetInfo;
    }
}
