namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass BrowserUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        BrowserUserControl(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer);

        Windows.Foundation.Collections.IObservableVector<CelestiaAppComponent.BrowserItemTab> RootItems{ get; };
    }
}
