namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass BrowserItemGetInfoArgs
    {
        CelestiaComponent.CelestiaSelection Selection{ get; };
    }

    [default_interface]
    runtimeclass BrowserItemUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        BrowserItemUserControl(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer, CelestiaAppComponent.BrowserItemTab item);

        Microsoft.UI.Xaml.Interop.IBindableObservableVector RootItem{ get; };
        Windows.Foundation.Collections.IObservableVector<CelestiaAppComponent.BrowserAction> Actions{ get; };

        event Windows.Foundation.EventHandler<BrowserItemGetInfoArgs> GetInfo;
    }
}
