// CommonWebUserControl.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

namespace CelestiaWinUI
{
    delegate Microsoft.UI.Xaml.Window WebWindowProvider();

    [default_interface]
    runtimeclass CommonWebParameter
    {
        CommonWebParameter(Windows.Foundation.Uri initailUri, Windows.Foundation.Collections.IVector<String> matchingQueryKeys, CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer, String contextDirectory, CelestiaAppComponent.JavascriptMessageACKCallback ackCallback, WebWindowProvider windowProvider);
        CommonWebParameter(Windows.Foundation.Uri initailUri, Windows.Foundation.Collections.IVector<String> matchingQueryKeys, CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer, String contextDirectory, CelestiaAppComponent.JavascriptMessageACKCallback ackCallback, WebWindowProvider windowProvider, Boolean updateWindowTitle);

        Windows.Foundation.Uri InitialUri{ get; };
        Windows.Foundation.Collections.IVector<String> MatchingQueryKeys{ get; };
        CelestiaComponent.CelestiaAppCore AppCore{ get; };
        CelestiaComponent.CelestiaRenderer Renderer{ get; };
        String ContextDirectory{ get; };
        CelestiaAppComponent.JavascriptMessageACKCallback ACKCallback{ get; };
        WebWindowProvider WindowProvider{ get; };
        Boolean UpdateWindowTitle{ get; };
    }

    [default_interface]
    runtimeclass CommonWebUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        CommonWebUserControl(CommonWebParameter args);
        void CloseWebViewIfNeeded();
    }
}
