// GotoObjectDialog.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass GotoObjectDialog : Microsoft.UI.Xaml.Controls.ContentDialog
    {
        GotoObjectDialog(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer);

        CelestiaComponent.CelestiaSelection Object{ get; };
        Single Latitude{ get; };
        Single Longitude{ get; };
        Double Distance{ get; };
        CelestiaComponent.CelestiaGotoLocationDistanceUnit UnitType{ get; };
        Windows.Foundation.Collections.IObservableVector<String> Units{ get; };
        Int32 Unit;
    }
}
