namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass InfoShowSubsystemArgs
    {
        CelestiaComponent.CelestiaSelection Selection{ get; };
        Boolean Handled;
    }

    [default_interface]
    runtimeclass InfoGetInfoArgs
    {
        CelestiaComponent.CelestiaSelection Selection{ get; };
        Boolean Handled;
    }

    [default_interface]
    runtimeclass InfoTemplateSelector : Microsoft.UI.Xaml.Controls.DataTemplateSelector
    {
        InfoTemplateSelector();
        Microsoft.UI.Xaml.DataTemplate Action;
        Microsoft.UI.Xaml.DataTemplate DropDown;
    }

    [default_interface]
    runtimeclass InfoControlStrip : Microsoft.UI.Xaml.Controls.UserControl
    {
        InfoControlStrip();
        Windows.Foundation.Collections.IObservableVector<CelestiaAppComponent.BrowserAction> Actions{ get; };
        CelestiaComponent.CelestiaAppCore AppCore;
        CelestiaComponent.CelestiaRenderer Renderer;
        CelestiaComponent.CelestiaSelection Selection;
        Boolean ShowsGetInfo;

        event Windows.Foundation.EventHandler<InfoShowSubsystemArgs> ShowSubsystem;
        event Windows.Foundation.EventHandler<InfoGetInfoArgs> GetInfo;
    }
}
