namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass InfoUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        InfoUserControl(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaSelection selection);
    }
}
