// ObserverModeDialog.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass ObserverModeStringConverter : Microsoft.UI.Xaml.Data.IValueConverter
    {
        ObserverModeStringConverter();
    }

    [default_interface]
    runtimeclass ObserverModeDialog : Microsoft.UI.Xaml.Controls.ContentDialog, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ObserverModeDialog(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer);
        Windows.Foundation.Collections.IObservableVector<CelestiaComponent.CoordinateSystem> CoordinateSystems{ get; };
        CelestiaComponent.CoordinateSystem SelectedCoordinateSystem;
        Microsoft.UI.Xaml.Visibility RefObjectTextBoxVisibility{ get; };
        Microsoft.UI.Xaml.Visibility TargetObjectTextBoxVisibility{ get; };
        CelestiaComponent.CelestiaSelection ReferenceObject{ get; };
        CelestiaComponent.CelestiaSelection TargetObject{ get; };
    }
}
