// ResourceManagerUserControl.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

import "CommonWebUserControl.idl";
import "InstalledItemListUserControl.idl";

namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass ResourceManagerUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        ResourceManagerUserControl(CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer, CelestiaAppComponent.ResourceManager resourceManager, WebWindowProvider windowProvider, GetAddonHandler getAddonHandler);
    }
}
