import "CommonWebUserControl.idl";

namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass SafeWebUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        SafeWebUserControl(CommonWebUserControlArgs args);
        void CloseWebViewIfNeeded();
    }
}
