// SettingCommonUserControl.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

namespace CelestiaWinUI
{
    delegate Microsoft.UI.Xaml.Window SettingWindowProvider();

    [default_interface]
    runtimeclass SettingParameter
    {
        SettingParameter(SettingWindowProvider windowProvider);
        SettingWindowProvider WindowProvider{ get; };
    }

    [default_interface]
    runtimeclass SettingTemplateSelector : Microsoft.UI.Xaml.Controls.DataTemplateSelector
    {
        SettingTemplateSelector();
        Microsoft.UI.Xaml.DataTemplate Toggle;
        Microsoft.UI.Xaml.DataTemplate Selection;
        Microsoft.UI.Xaml.DataTemplate Slider;
        Microsoft.UI.Xaml.DataTemplate Header;
        Microsoft.UI.Xaml.DataTemplate DataDirectory;
        Microsoft.UI.Xaml.DataTemplate ConfigFile;
    }

    [default_interface]
    runtimeclass SettingCommonUserControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        SettingCommonUserControl(Windows.Foundation.Collections.IObservableVector<Object> settingItems, Boolean showRestartHint, SettingParameter parameter);
        Windows.Foundation.Collections.IObservableVector<Object> Items{ get; };
        Boolean ShowRestartHint{ get; };
    }
}
