// TourGuideWindow.idl
//
// Copyright (C) 2025, Celestia Development Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.

namespace CelestiaWinUI
{
    [default_interface]
    runtimeclass TourGuideWindow : Microsoft.UI.Xaml.Window
    {
        TourGuideWindow(CelestiaComponent.CelestiaDestination[] destinations, CelestiaComponent.CelestiaAppCore appCore, CelestiaComponent.CelestiaRenderer renderer);
        Windows.Foundation.Collections.IObservableVector<CelestiaComponent.CelestiaDestination> Destinations{ get; };
    }
}
